[package]
name = "reducer-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
reducer-sys = { path = "../reducer-sys" }
reducer = { workspace = true }

[[bin]]
name = "reducer"
path = "src/main.rs"
